---

- name: tasks/install_composer
  block:

    - name: tasks/install_composer > Stat bin
      stat:
        path: "{{ item.shared_dir }}/composer"
      register: __deploy_composer_bin_stat_result

    - name: tasks/install_composer > Download installer
      get_url:
        url:  https://getcomposer.org/installer
        dest: /tmp
      when: not __deploy_composer_bin_stat_result.stat.exists

    - name: tasks/install_composer > Install
      command: "php /tmp/installer --install-dir=\"{{ item.shared_dir }}\" --filename=\"composer\" --disable-tls"
      when: not __deploy_composer_bin_stat_result.stat.exists

    - name: tasks/install_composer > Remove installer
      file:
        path:  /tmp/installer
        state: absent
      when: not __deploy_composer_bin_stat_result.stat.exists

    - name: tasks/install_composer > Self update
      shell: "{{ item.shared_dir }}/composer selfupdate --no-interaction"
      when: __deploy_composer_bin_stat_result.stat.exists
      register: __deploy_composer_self_update_result
      changed_when: __deploy_composer_self_update_result.stderr | search('Updating')
      failed_when: false

    - name: tasks/install_composer > Link to current release
      file:
        src: "{{ item.shared_dir }}/composer"
        dest: "{{ item.dir }}/composer"
        state: link
