---

- name: tasks/symfony_assets_version
  block:

    - name: tasks/symfony_assets_version > Set assets version
      set_fact:
        __deploy_symfony_assets_version: "{{
          deploy_strategy_git_head
            if (item.options == 'git_head' and deploy_strategy_git_head) else
          deploy_helper.new_release
        }}"

    - name: tasks/symfony_assets_version > Replace assets_version in parameters.yml
      lineinfile:
        dest: "{{ item.dir }}/app/config/parameters.yml"
        regexp: "^(\\s*)assets_version:"
        line: "\\1assets_version: {{ __deploy_symfony_assets_version }}"
        backrefs: yes
