---

- name: tasks/symfony_assets_version_file
  block:

    - name: tasks/symfony_assets_version_file > Set assets version
      set_fact:
        __deploy_symfony_assets_version: "{{
          deploy_strategy_git_head
            if (item.options == 'git_head' and deploy_strategy_git_head) else
          deploy_helper.new_release
        }}"

    - name: tasks/symfony_assets_version_file > Generate assets_version.yml
      copy:
        dest: "{{ item.dir }}/app/config/assets_version.yml"
        force: yes
        content: |
          parameters:
            assets_version: {{ __deploy_symfony_assets_version }}
